### ISSUE TITLE
Moon Phase crashes ;_;

### ISSUE THREAD

**Issue by metbic** [andviane/moon#2]
Dear developers of Moon Phase,
I'm very sorry to bring this up again. But it crashes indeed directly after its start (ice cream sandwich on a Sony Xperia Miro). Would you suggest to get an extra Java runtime for additional bases? Or is it something else? Here, have a logcat:

--------- beginning of /dev/log/main
D/memalloc( 1551): /dev/pmem: Unmapping buffer base:0x52013000 size:5214208 offset:4956160
D/memalloc(  122): /dev/pmem: Freeing buffer base:0x419c5000 size:258048 offset:4956160 fd:34
D/memalloc( 1551): /dev/pmem: Unmapping buffer base:0x5250c000 size:5472256 offset:5214208
--------- beginning of /dev/log/system
W/InputManagerService(  374): Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@411fab30
D/memalloc(  122): /dev/pmem: Allocated buffer base:0x4150b000 size:49152 offset:5472256 fd:34
D/memalloc( 1551): /dev/pmem: Mapped buffer base:0x52013000 size:5521408 offset:5472256 fd:63
I/Adreno200-EGLSUB(  122): CreateImage:896: Android Image
I/Adreno200-EGLSUB(  122): GetImageAttributes:1105: RGBA_8888
D/memalloc(  122): /dev/pmem: Freeing buffer base:0x41a04000 size:258048 offset:5214208 fd:43
D/memalloc( 1551): /dev/pmem: Unmapping buffer base:0x52013000 size:5521408 offset:5472256
I/ActivityManager(  374): START {act=android.intent.action.MAIN cat=[android.intent.category.HOME] flg=0x10200000 cmp=com.sonyericsson.home/.HomeActivity} from pid 374
I/WindowManager(  374): SCREENLAYOUT_SIZE (1:small, 2:normal, 3:large, 4:xlarge) 2
D/memalloc(  122): /dev/pmem: Freeing buffer base:0x41a43000 size:49152 offset:5472256 fd:34
D/-heap   (  374): GC_EXPLICIT freed 304K, 20% free 12326K/15395K, paused 4ms+9ms
D/ConnectivityService(  374): getMobileDataEnabled returning true
D/ConnectivityService(  374): getMobileDataEnabled returning true
D/ConnectivityService(  374): getMobileDataEnabled returning true
D/memalloc(  122): /dev/pmem: Allocated buffer base:0x4150b000 size:614400 offset:4956160 fd:34
D/ConnectivityService(  374): getMobileDataEnabled returning true
D/ConnectivityService(  374): getMobileDataEnabled returning true
D/memalloc(  571): /dev/pmem: Mapped buffer base:0x51bb3000 size:5570560 offset:4956160 fd:78
I/Adreno200-EGLSUB(  122): CreateImage:896: Android Image
I/Adreno200-EGLSUB(  122): GetImageAttributes:1105: RGBA_8888
D/memalloc( 1551): /dev/pmem: Unmapping buffer base:0x516d0000 size:4935680 offset:4321280
D/memalloc(  122): /dev/pmem: Freeing buffer base:0x4192a000 size:614400 offset:4321280 fd:37
D/memalloc( 1551): /dev/pmem: Unmapping buffer base:0x51598000 size:614400 offset:0
W/InputManagerService(  374): Starting input on non-focused client com.android.internal.view.IInputMethodClient$Stub$Proxy@415ec700 (uid=10171 pid=1551)
D/memalloc(  122): /dev/pmem: Freeing buffer base:0x4150b000 size:614400 offset:0 fd:31
D/memalloc(  122): /dev/pmem: Allocated buffer base:0x4150b000 size:614400 offset:4321280 fd:31
D/ConnectivityService(  374): getMobileDataEnabled returning true
D/memalloc(  571): /dev/pmem: Mapped buffer base:0x52581000 size:4935680 offset:4321280 fd:86
I/Adreno200-EGLSUB(  122): CreateImage:896: Android Image
I/Adreno200-EGLSUB(  122): GetImageAttributes:1105: RGBA_8888
D/ConnectivityService(  374): getMobileDataEnabled returning true
D/ConnectivityService(  374): getMobileDataEnabled returning true
D/ConnectivityService(  374): getMobileDataEnabled returning true
D/-heap   (  571): GC_FOR_ALLOC freed 1635K, 21% free 10922K/13667K, paused 39ms
D/ConnectivityService(  374): getMobileDataEnabled returning true
D/ConnectivityService(  374): getMobileDataEnabled returning true
D/-heap   (  571): GC_FOR_ALLOC freed 718K, 20% free 11070K/13667K, paused 35ms
D/-heap   (  571): GC_FOR_ALLOC freed 615K, 19% free 11128K/13667K, paused 35ms
D/-heap   (  571): GC_FOR_ALLOC freed 610K, 19% free 11120K/13667K, paused 33ms
I/ActivityManager(  374): START {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=akk.astro.droid.moonphase/.MoonActivity bnds=[83,76][158,186]} from pid 571
D/memalloc(  122): /dev/pmem: Allocated buffer base:0x4150b000 size:614400 offset:0 fd:37
D/memalloc(  374): /dev/pmem: Mapped buffer base:0x5499a000 size:614400 offset:0 fd:274
I/Adreno200-EGLSUB(  122): CreateImage:896: Android Image
I/Adreno200-EGLSUB(  122): GetImageAttributes:1105: RGBA_8888
I/ActivityManager(  374): Start proc akk.astro.droid.moonphase for activity akk.astro.droid.moonphase/.MoonActivity: pid=1587 uid=10198 gids={}
I/WindowManager(  374): SCREENLAYOUT_SIZE (1:small, 2:normal, 3:large, 4:xlarge) 2
W/ResourceType(  374): Skipping entry 0x7f04001b in package table 0 because it is not complex!
W/ResourceType(  374): Skipping entry 0x7f04003d in package table 0 because it is not complex!
D/memalloc(  571): /dev/pmem: Unmapping buffer base:0x51bb3000 size:5570560 offset:4956160
D/memalloc(  122): /dev/pmem: Freeing buffer base:0x419c5000 size:614400 offset:4956160 fd:34
D/memalloc(  571): /dev/pmem: Unmapping buffer base:0x52581000 size:4935680 offset:4321280
D/memalloc(  122): /dev/pmem: Freeing buffer base:0x4192a000 size:614400 offset:4321280 fd:31
I/Adreno200-EGLSUB( 1587): ConfigWindowMatch:2081: Format RGBA_8888.
D/memalloc(  122): /dev/pmem: Allocated buffer base:0x4150b000 size:614400 offset:4321280 fd:31
D/memalloc( 1587): /dev/pmem: Mapped buffer base:0x51686000 size:4935680 offset:4321280 fd:63
W/dalvikvm( 1587): threadid=1: thread exiting with uncaught exception (group=0x40aee9f0)
E/AndroidRuntime( 1587): FATAL EXCEPTION: main
E/AndroidRuntime( 1587): java.lang.IllegalArgumentException: May 15 17:05:37 PST 1997
E/AndroidRuntime( 1587):    at akk.astro.droid.moonphase.StarDate.setTime(StarDate.java:88)
E/AndroidRuntime( 1587):    at akk.astro.droid.moonphase.StarDate.<init>(StarDate.java:37)
E/AndroidRuntime( 1587):    at akk.astro.droid.moonphase.StarDate.setTime(StarDate.java:52)
E/AndroidRuntime( 1587):    at akk.astro.droid.moonphase.StarDate.<init>(StarDate.java:37)
E/AndroidRuntime( 1587):    at akk.astro.droid.moonphase.MoonPhase.getPhaseAngle(MoonPhase.java:32)
E/AndroidRuntime( 1587):    at akk.astro.droid.moonphase.MoonView.onDraw(MoonView.java:61)
E/AndroidRuntime( 1587):    at android.view.View.draw(View.java:11054)
E/AndroidRuntime( 1587):    at android.view.View.getDisplayList(View.java:10493)
E/AndroidRuntime( 1587):    at android.view.ViewGroup.drawChild(ViewGroup.java:2958)
E/AndroidRuntime( 1587):    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2596)
E/AndroidRuntime( 1587):    at android.view.View.getDisplayList(View.java:10491)
E/AndroidRuntime( 1587):    at android.view.ViewGroup.drawChild(ViewGroup.java:2958)
E/AndroidRuntime( 1587):    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2596)
E/AndroidRuntime( 1587):    at android.view.View.getDisplayList(View.java:10491)
E/AndroidRuntime( 1587):    at android.view.ViewGroup.drawChild(ViewGroup.java:2958)
E/AndroidRuntime( 1587):    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2596)
E/AndroidRuntime( 1587):    at android.view.View.getDisplayList(View.java:10491)
E/AndroidRuntime( 1587):    at android.view.ViewGroup.drawChild(ViewGroup.java:2958)
E/AndroidRuntime( 1587):    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2596)
E/AndroidRuntime( 1587):    at android.view.View.draw(View.java:11057)
E/AndroidRuntime( 1587):    at android.widget.FrameLayout.draw(FrameLayout.java:463)
E/AndroidRuntime( 1587):    at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2145)
E/AndroidRuntime( 1587):    at android.view.View.getDisplayList(View.java:10493)
E/AndroidRuntime( 1587):    at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:880)
E/AndroidRuntime( 1587):    at android.view.ViewRootImpl.draw(ViewRootImpl.java:1911)
E/AndroidRuntime( 1587):    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1635)
E/AndroidRuntime( 1587):    at android.view.ViewRootImpl.handleMessage(ViewRootImpl.java:2455)
E/AndroidRuntime( 1587):    at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 1587):    at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime( 1587):    at android.app.ActivityThread.main(ActivityThread.java:4424)
E/AndroidRuntime( 1587):    at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 1587):    at java.lang.reflect.Method.invoke(Method.java:511)
E/AndroidRuntime( 1587):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:817)
E/AndroidRuntime( 1587):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:584)
E/AndroidRuntime( 1587):    at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime( 1587): Caused by: java.text.ParseException: Unparseable date: "May 15 17:05:37 PST 1997" (at offset 0)
E/AndroidRuntime( 1587):    at java.text.DateFormat.parse(DateFormat.java:626)
E/AndroidRuntime( 1587):    at akk.astro.droid.moonphase.StarDate.setTime(StarDate.java:85)
E/AndroidRuntime( 1587):    ... 34 more
W/ActivityManager(  374):   Force finishing activity akk.astro.droid.moonphase/.MoonActivity
W/ActivityManager(  374): sendCrashtoMTBF!!
D/memalloc(  122): /dev/pmem: Allocated buffer base:0x4150b000 size:163840 offset:4956160 fd:34
D/memalloc(  374): /dev/pmem: Mapped buffer base:0x57a1e000 size:5120000 offset:4956160 fd:288
I/Adreno200-EGLSUB(  122): CreateImage:896: Android Image
I/Adreno200-EGLSUB(  122): GetImageAttributes:1105: RGBA_8888
I/BatteryService(  374): start UEvent update
I/BatteryService(  374): finished UEvent update
I/WindowManager(  374): SCREENLAYOUT_SIZE (1:small, 2:normal, 3:large, 4:xlarge) 2
W/ActivityManager(  374): Activity pause timeout for ActivityRecord{41618098 akk.astro.droid.moonphase/.MoonActivity}
D/ConnectivityService(  374): getMobileDataEnabled returning true
D/memalloc(  122): /dev/pmem: Allocated buffer base:0x4150b000 size:614400 offset:614400 fd:43
D/memalloc(  571): /dev/pmem: Mapped buffer base:0x5183d000 size:1228800 offset:614400 fd:78
I/Adreno200-EGLSUB(  122): CreateImage:896: Android Image
I/Adreno200-EGLSUB(  122): GetImageAttributes:1105: RGBA_8888
D/ConnectivityService(  374): getMobileDataEnabled returning true
D/ConnectivityService(  374): getMobileDataEnabled returning true
D/ConnectivityService(  374): getMobileDataEnabled returning true
D/ConnectivityService(  374): getMobileDataEnabled returning true
D/memalloc(  122): /dev/pmem: Allocated buffer base:0x4150b000 size:163840 offset:5120000 fd:55
D/memalloc(  374): /dev/pmem: Mapped buffer base:0x57f00000 size:5283840 offset:5120000 fd:291
I/Adreno200-EGLSUB(  122): CreateImage:896: Android Image
I/Adreno200-EGLSUB(  122): GetImageAttributes:1105: RGBA_8888
D/ConnectivityService(  374): getMobileDataEnabled returning true
D/ConnectivityService(  374): getMobileDataEnabled returning true
D/ConnectivityService(  374): getMobileDataEnabled returning true
D/ConnectivityService(  374): getMobileDataEnabled returning true
D/-heap   (  571): GC_FOR_ALLOC freed 1086K, 19% free 11151K/13667K, paused 35ms
D/ConnectivityService(  374): getMobileDataEnabled returning true
D/ConnectivityService(  374): getMobileDataEnabled returning true
I/WindowManager(  374): WIN DEATH: Window{4169ca98 akk.astro.droid.moonphase/akk.astro.droid.moonphase.MoonActivity paused=false}
I/ActivityManager(  374): Process akk.astro.droid.moonphase (pid 1587) has died.
D/memalloc(  374): /dev/pmem: Unmapping buffer base:0x5499a000 size:614400 offset:0
D/memalloc(  122): /dev/pmem: Freeing buffer base:0x4192a000 size:614400 offset:4321280 fd:31
D/memalloc(  122): /dev/pmem: Freeing buffer base:0x4150b000 size:614400 offset:0 fd:37
D/memalloc(  374): /dev/pmem: Unmapping buffer base:0x57f00000 size:5283840 offset:5120000
D/memalloc(  122): /dev/pmem: Freeing buffer base:0x419ed000 size:163840 offset:5120000 fd:55
D/memalloc(  374): /dev/pmem: Unmapping buffer base:0x57a1e000 size:5120000 offset:4956160
D/memalloc(  122): /dev/pmem: Freeing buffer base:0x419c5000 size:163840 offset:4956160 fd:34
I/ActivityManager(  374): START {act=android.intent.action.MAIN cat=[android.intent.category.HOME] flg=0x10200000 cmp=com.sonyericsson.home/.HomeActivity} from pid 374
D/ConnectivityService(  374): getMobileDataEnabled returning true
D/memalloc(  122): /dev/pmem: Allocated buffer base:0x4150b000 size:614400 offset:0 fd:31
D/memalloc(  571): /dev/pmem: Mapped buffer base:0x51969000 size:614400 offset:0 fd:86
I/Adreno200-EGLSUB(  122): CreateImage:896: Android Image
I/Adreno200-EGLSUB(  122): GetImageAttributes:1105: RGBA_8888
D/ConnectivityService(  374): getMobileDataEnabled returning true
D/ConnectivityService(  374): getMobileDataEnabled returning true
D/ConnectivityService(  374): getMobileDataEnabled returning true
D/ConnectivityService(  374): getMobileDataEnabled returning true
D/ConnectivityService(  374): getMobileDataEnabled returning true
D/ConnectivityService(  374): getMobileDataEnabled returning true
D/ConnectivityService(  374): getMobileDataEnabled returning true
D/ConnectivityService(  374): getMobileDataEnabled returning true
D/ConnectivityService(  374): getMobileDataEnabled returning true
D/ConnectivityService(  374): getMobileDataEnabled returning true
I/ActivityManager(  374): START {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.jtb.alogcat/.LogActivity bnds=[84,324][158,404]} from pid 571
I/WindowManager(  374): SCREENLAYOUT_SIZE (1:small, 2:normal, 3:large, 4:xlarge) 2
D/memalloc(  122): /dev/pmem: Allocated buffer base:0x4150b000 size:614400 offset:4321280 fd:34
D/memalloc( 1551): /dev/pmem: Mapped buffer base:0x51698000 size:4935680 offset:4321280 fd:72
I/Adreno200-EGLSUB(  122): CreateImage:896: Android Image
I/Adreno200-EGLSUB(  122): GetImageAttributes:1161: RGBX_8888
W/ResourceType(  374): Skipping entry 0x7f04001f in package table 0 because it is not complex!
D/memalloc(  571): /dev/pmem: Unmapping buffer base:0x51969000 size:614400 offset:0
D/memalloc(  122): /dev/pmem: Freeing buffer base:0x4150b000 size:614400 offset:0 fd:31
D/memalloc(  571): /dev/pmem: Unmapping buffer base:0x5183d000 size:1228800 offset:614400
D/memalloc(  122): /dev/pmem: Allocated buffer base:0x4150b000 size:49152 offset:0 fd:31
D/memalloc( 1551): /dev/pmem: Mapped buffer base:0x4f743000 size:49152 offset:0 fd:67
I/Adreno200-EGLSUB(  122): CreateImage:896: Android Image
I/Adreno200-EGLSUB(  122): GetImageAttributes:1105: RGBA_8888
D/memalloc(  122): /dev/pmem: Allocated buffer base:0x4150b000 size:614400 offset:4956160 fd:37
D/memalloc( 1551): /dev/pmem: Mapped buffer base:0x52013000 size:5570560 offset:4956160 fd:70
I/Adreno200-EGLSUB(  122): CreateImage:896: Android Image
I/Adreno200-EGLSUB(  122): GetImageAttributes:1161: RGBX_8888
D/memalloc(  122): /dev/pmem: Freeing buffer base:0x415a1000 size:614400 offset:614400 fd:43
D/-heap   ( 1551): GC_CONCURRENT freed 2278K, 35% free 6949K/10531K, paused 2ms+7ms

**Comment by andviane** [comment]
This is really great, thanks for providing this valuable information. Seems that the date "May 15 17:05:37 PST 1997" cannot be parsed on your device, probably because of the locale issues. I will investigate and hope to post the fix ASAP.

**Comment by andviane** [comment]
It seems that these strange strings are parsed without much need. I have removed unnecessary parsings. This has no impact on the moon image on my device. When possible, I  would like to ask you to test.

**Comment by metbic** [comment]
test? sure.

**Comment by metbic** [comment]
btw 1.2 works fine

**Comment by andviane** [comment]
Thanks a lot! I am closing this as fixed.
